# https://yesjuhee.tistory.com/18
# AI가 응답할 때 사용할 기본 언어를 설정합니다. (예: ko-KR, en-US)
language: "ko-KR"

# 안정성 우선, 실험 기능 OFF
early_access: false

# AI의 페르소나와 응답 톤앤매너를 상세하게 지시합니다. 최대 200자까지 작성할 수 있습니다.
tone_instructions: >
  당신은 iOS 개발자의 성장을 돕는 시니어 엔지니어입니다. 목표는 코드 품질 개선을 통해 개발자가 한 단계 성장하도록 돕는 것입니다.
  1. 피드백은 명확하고 구체적으로 작성하며, Swift/iOS 관점에서 문제의 원인과 개선 방법을 제시하세요.
  2. 리뷰는 교육적으로 작성하고, 관련 개념과 Apple 공식 문서 또는 WWDC 자료를 함께 추천하세요.
  3. 비판보다 개선 중심의 제안을 우선하세요.
  4. 칭찬은 짧고 위트 있게 전달하세요.

# 코드 리뷰 기능 세부 설정
reviews:
  # 리뷰의 전반적인 스타일을 설정합니다. 'chill'은 비교적 덜 엄격하고 부드러운 톤을 의미합니다.
  profile: "chill"
  
  # 리뷰 시작했다는 확인 메시지 제거
  show_in_progress_messages: false
  
  # CodeRabbit의 코멘트를 모두 `resolve`하면, 자동으로 Approve를 하는 기능입니다.
  # PR은 2명의 리뷰어의 Approve 후 가능하다는 팀 컨벤션이 있기 때문에 false로 설정했습니다.
  request_changes_workflow: false
  
  # PR의 전체적인 변경 사항에 대한 고수준의 요약(summary)을 생성할지 여부입니다.
  high_level_summary: true
  
  # 변경된 각 파일에 대한 요약을 생성할지 여부입니다.
  # PR이 너무 길어지는 것을 방지하기 위해 비활성화했습니다.
  changed_files_summary: false
  
  # 코드의 실행 흐름을 보여주는 시퀀스 다이어그램을 생성할지 여부입니다.
  sequence_diagrams: true
  
  # PR에 연결된 이슈(Issue)를 분석하여 리뷰 컨텍스트에 활용할지 여부입니다.
  assess_linked_issues: true
  
  # 연관된 다른 이슈를 찾아서 링크할지 여부입니다.
  related_issues: false
  
  # 연관된 다른 PR을 찾아서 링크할지 여부입니다.
  related_prs: false
  
  # PR에 적절한 레이블(e.g., 'bug', 'enhancement')을 제안할지 여부입니다.
  suggested_labels: false
  
  # 제안된 레이블을 자동으로 PR에 적용할지 여부입니다.
  auto_apply_labels: false
  
  # 이 PR을 리뷰할 만한 적절한 동료 리뷰어를 추천할지 여부입니다.
  suggested_reviewers: false
  
  # 추천된 리뷰어를 자동으로 할당할지 여부입니다.
  auto_assign_reviewers: false
  
  # 리뷰 요약에 위트 있는 시(poem)를 포함할지 여부입니다.
  # 몇몇 팀원들의 반대가 있었지만, CodeRabbit이 써주는 시가 귀여워서 개인 취향으로 강력 주장해서 활성화시켰습니다.
  poem: true
  
  # 특정 파일 경로에 따라 다른 리뷰 지침을 적용합니다.
  # 모노레포를 사용하는 프로젝트였기 때문에 각 분야마다 다른 인스트럭션을 작성했습니다.
  path_instructions:
  - path: PopPang/Sources/App/**
    instructions: |
      1. 앱 진입 지점(AppDelegate/SceneDelegate/SwiftUI App)의 역할이 과도하지 않은지, 초기화 로직(Firebase, DI 등)이 적절히 분리되어 있는지 검토해주세요.
      2. 환경별(Debug/Release) 분기, 전역 상태 사용 여부를 점검하고 개선 방향을 제안해주세요.

  - path: PopPang/Sources/Domain/**
    instructions: |
      1. Domain 계층이 UI/플랫폼 의존성을 갖지 않는지 확인해주세요.
      2. Entity, UseCase, Protocol의 책임이 명확한지, 비즈니스 규칙이 분산되지 않았는지 리뷰해주세요.
      3. 테스트 가능한 구조인지(Unit Test 기준)와 네이밍의 명확성을 함께 검토해주세요.

  - path: PopPang/Sources/Data/**
    instructions: |
      1. Repository 구현이 Domain Protocol을 정확히 따르는지, 외부 의존성(API, DB, Firebase 등)이 Data 계층에만 머무르는지 확인해주세요.
      2. 비동기 처리(async/await, completion)의 일관성, 에러 처리 전략을 중점적으로 리뷰해주세요.
      3. Mocking이 가능한 구조인지와 RepositoryTest 작성 가능 여부를 함께 검토해주세요.

  - path: PopPang/Sources/Presentation/**
    instructions: |
      1. View/ViewModel(MVVM)의 책임 분리가 명확한지, ViewModel이 과도하게 비대해지지 않았는지 검토해주세요.
      2. SwiftUI의 상태 관리(@State, @Binding, @ObservedObject 등) 또는 UIKit 생명주기 사용이 적절한지 확인해주세요.
      3. 불필요한 리렌더링, 메인 스레드 오남용, 네비게이션 처리 방식(Coordinator 등)을 성능 관점에서 리뷰해주세요.
      4. @MainActor 사용 여부와 비동기 작업에서 UI 업데이트 위치가 적절한지 확인해주세요.

  - path: PopPang/Sources/DesignSystem/**
    instructions: |
      1. 공통 UI 컴포넌트가 재사용 가능하게 설계되어 있는지 확인해주세요.
      2. 색상, 폰트, 버튼 등 디자인 요소가 하드코딩되지 않고 일관성 있게 관리되는지 검토해주세요.
      3. 특정 화면에 종속된 컴포넌트가 DesignSystem에 포함되어 있다면 분리 제안을 해주세요.

  - path: PopPang/Sources/Util/**
    instructions: |
      1. Util이 범용적인 기능만 포함하고 있는지, 특정 도메인/화면 로직이 섞여 있지 않은지 확인해주세요.
      2. 확장(extension)이 과도하거나 네이밍 충돌 가능성이 없는지 검토해주세요.

  - path: PopPang/RepositoryTest/**
    instructions: |
      1. Repository 테스트가 실제 네트워크/외부 의존성 없이 동작하는지(Mock/Stubs) 확인해주세요.
      2. 비동기 테스트에서 타임아웃, expectation 누락 가능성이 없는지 검토해주세요.
      3. 테스트 목적이 명확하고 실패 원인을 빠르게 파악할 수 있는지 리뷰해주세요.

  - path: PopPangUITests/**
    instructions: |
      1. UI 테스트가 핵심 사용자 플로우 위주로 구성되어 있는지 확인해주세요.
      2. 불필요하게 느리거나 flaky한 테스트가 있는지, 안정화 방안을 제안해주세요.
      3. CI 환경에서 실행 가능하도록 의존성(권한, 네트워크, 초기 상태)이 적절히 제어되는지 검토해주세요.

# ---------------------------------------------------------------- #
# 자동 리뷰 트리거 설정
# ---------------------------------------------------------------- #
#auto_review:
#    # PR이 생성됐을 때
#    # `@coderabbitai review`를 코멘트에 입력하면 리뷰를 시작합니다.
#    enabled: false
#    
#    # 이미 리뷰가 진행된 PR에 새로운 커밋이 추가될 때, 변경된 부분에 대해서만 자동으로 리뷰를 진행할지 여부입니다.
#    auto_incremental_review: false

# ---------------------------------------------------------------- #
# 채팅 기능 설정
# ---------------------------------------------------------------- #
chat:
  # 사용자가 @coderabbitai 태그를 지정하지 않아도 자동으로 답글을 달 수 있도록 설정합니다.
  auto_reply: false

# ---------------------------------------------------------------- #
# CodeRabbit의 지식 기반(Knowledge Base) 설정
# ---------------------------------------------------------------- #
knowledge_base:
  # 웹 검색을 통해 최신 정보나 문서를 참조할 수 있도록 허용할지 여부입니다.
  web_search:
    enabled: true
  
  # CodeRabbit이 대화나 리뷰를 통해 학습한 내용을 어디에 저장하고 참조할지 범위를 설정합니다. 'local'은 현재 레포지토리에 한정됨을 의미합니다.
  learnings:
    scope: local
  
  # 이슈 정보를 참조할 범위를 설정합니다.
  issues:
    scope: local
  
  # 풀 리퀘스트 정보를 참조할 범위를 설정합니다.
  pull_requests:
    scope: local
