import Foundation

public enum LocalizationKey: String {
    case greetingHello = "greeting.hello"
    case homeDescription = "home.description"
    case homeSegmentFeed = "home.segment.feed"
    case homeSegmentCalendar = "home.segment.calendar"
    case homeNavigationBack = "home.navigation.back"
    case homeFeedBubbleAddPhoto = "home.feed.bubble.add_photo"
    case homeFeedBubbleDoneToday = "home.feed.bubble.done_today"
    case homeFeedDeleteAlertTitle = "home.feed.delete.alert.title"
    case homeFeedDeleteAlertMessage = "home.feed.delete.alert.message"
    case homeFeedCameraActionCamera = "home.feed.camera.action.camera"
    case homeFeedCameraActionAlbum = "home.feed.camera.action.album"
    case memberFamilyCount = "member.family.count"
    case memberFamilyCountValue = "member.family.count.value"
    case commonBack = "common.back"
    case commonCancel = "common.cancel"
    case commonClose = "common.close"
    case commonDelete = "common.delete"
    case commonNext = "common.next"
    case commonDone = "common.done"
    case commonPreviewNickname = "common.preview.nickname"
    case commonPreviewRelativeTime = "common.preview.relative_time"
    case dateRelativeJustNow = "date.relative.just_now"
    case commentTitle = "comment.title"
    case commentInputPlaceholder = "comment.input.placeholder"
    case commentSend = "comment.send"
    case commentPlaceholderPreview = "comment.placeholder.preview"
    case authSigninAppName = "auth.signin.app_name"
    case authSigninKakao = "auth.signin.kakao"
    case authSigninApple = "auth.signin.apple"
    case authGroupSelectTitle = "auth.group.select.title"
    case authGroupSelectEnterTop = "auth.group.select.enter.top"
    case authGroupSelectEnterBottom = "auth.group.select.enter.bottom"
    case authGroupSelectHostTop = "auth.group.select.host.top"
    case authGroupSelectHostBottom = "auth.group.select.host.bottom"
    case authGroupEnterTitle = "auth.group.enter.title"
    case authGroupEnterPlaceholder = "auth.group.enter.placeholder"
    case authGroupHostTitle = "auth.group.host.title"
    case authGroupHostPlaceholder = "auth.group.host.placeholder"
    case memberInviteShareMessage = "member.invite.share.message"
    case onboardingPage1Title = "onboarding.page1.title"
    case onboardingPage1Subtitle = "onboarding.page1.subtitle"
    case onboardingPage2Title = "onboarding.page2.title"
    case onboardingPage2Subtitle = "onboarding.page2.subtitle"
    case onboardingPage3Title = "onboarding.page3.title"
    case onboardingPage3Subtitle = "onboarding.page3.subtitle"
    case onboardingPage4Title = "onboarding.page4.title"
    case onboardingPage4Subtitle = "onboarding.page4.subtitle"
    case profileNicknameEditTitle = "profile.nickname_edit.title"
    case profileNicknameEditSubtitle = "profile.nickname_edit.subtitle"
    case profileNicknameEditPlaceholder = "profile.nickname_edit.placeholder"
    case profileNicknameEditComplete = "profile.nickname_edit.complete"
    case profileSettingSectionApp = "profile.setting.section.app"
    case profileSettingSectionInfo = "profile.setting.section.info"
    case profileSettingSectionAccount = "profile.setting.section.account"
    case profileSettingNotification = "profile.setting.notification"
    case profileSettingVersion = "profile.setting.version"
    case profileSettingPrivacy = "profile.setting.privacy"
    case profileSettingAnnounce = "profile.setting.announce"
    case profileSettingWithdraw = "profile.setting.withdraw"
    case profileSettingLogout = "profile.setting.logout"
    case profileSettingWithdrawAlertTitle = "profile.setting.withdraw.alert.title"
    case profileSettingWithdrawAlertMessage = "profile.setting.withdraw.alert.message"
    case profileSettingWithdrawAlertConfirm = "profile.setting.withdraw.alert.confirm"
    case profileSettingNotificationAlertTitle = "profile.setting.notification.alert.title"
    case profileSettingNotificationAlertMessage = "profile.setting.notification.alert.message"
    case profileSettingNotificationAlertOpenSettings = "profile.setting.notification.alert.open_settings"

    public var localized: String {
        rawValue.localized()
    }
}
